_target_: diffcsp.pl_modules.model.CrystGNN_Supervise
use_orientation: false
hidden_dim: 128
fc_num_layers: 4
use_pe: false
task: ${data.task}
num_targets: ${data.num_targets}

defaults:
  - encoder: dimenet
